# Generated by Django 4.2.1 on 2023-05-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_order_orderitems"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="customer_name",
        ),
    ]
