# Generated by Django 4.2.1 on 2023-05-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_remove_cart_customer_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
