# Generated by Django 4.2.1 on 2023-05-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_cart_total_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customer",
            new_name="user",
        ),
    ]
