# Generated by Django 4.2.1 on 2023-06-04 18:45

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_remove_product_image_file_name_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_url",
            field=models.ImageField(
                blank=True, null=True, upload_to=shop.models.upload_to
            ),
        ),
    ]
